server:
     # 指定服务器端口号
     port: 8081
spring:
     thymeleaf:
         # 禁止浏览器缓存
         cache: false
         mode: HTML5
     datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
         username: root
         password: mysql
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: org.springboot.entity